spring:
  application:
    name: Courigistics
    frontend-url: ${FRONTEND_URL:http://localhost:5173}
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
    # Common configurations
  jpa:
    open-in-view: false
    defer-datasource-initialization: true # Defer data.sql until after hibernate ddl
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  data:
    jdbc:
      repositories:
        enabled: false

server:
  port: 8080

# JWT Configuration with environment variables
jwt:
  secret-key: ${JWT_SECRET_KEY}
  #  encryption-key: ${JWT_ENCRYPTION_KEY} # <--- Our encryption key
  signing-key: ${JWT_SIGNING_KEY} # <--- New: Our signing key
  access-token-expiration: ${JWT_ACCESS_EXPR}
  refresh-token-expiration: ${JWT_REFRESH_EXPR}
  security:
    include-minimal-claims: true
    validate-issuer: true
    validate-environment: true
    # added Key validation
    min-key-length: 32 # Minimum 256 bits

# Application-specific properties
app:
  # Verification Token properties
  verification-token:
    expiration-minutes: 15 # token expires after 15 minutes
    token-length: 32 # length of the random bytes used for token generation

  # courier-specific configuration
  courier:
    approval:
      auto-approve: false # set to true for testing without admin approval
      require-vehicle-for-freelancer: true # freelancers must provide vehicles details
    employee-id:
      prefix: "COU" # Employee ID format: COU-YYYY-XXXX
      year-format: "yyyy" # year format in employee ID
      sequence-length: 4 # Number of digits in sequence (e.g., 0001)

  # default depot assignment (can be overridden by admin)
    default-depot:
      code: "NBO-MAIN"# default depot code for new couriers


# Actuator endpoints enabling
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: ${spring.application.name}
    version: ${project.version:0.0.1-SNAPSHOT}
    description: "Fileflow secure media management API"
  author:
    name: "Stephen Salano"
